apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: https://github.com/sree77hari/gitops.git
type: kubernetes.io/basic-auth
stringData:
  username: sree77hari
  password: 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
---
apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: srereddy
  password: Reddy@321
