apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-task
spec:
  params:
  - name: configGitUrl
  - name: environment
  - name: imageName

  workspaces:
  - name: gitops-workspace
  
  steps:
  - name: update-yaml
    image: quay.io/srereddy/sample:git-v2.26.2
    workingDir: "$(workspaces.gitops-workspace.path)"
    script: |
      #!/usr/bin/env sh
      set -e

      git config --global user.email "sree77hari@gmail.com"
      git config --global user.name "sree77hari"

      rm -rf gitops
      git clone -b main $(inputs.params.configGitUrl) gitops
      cd gitops/$(inputs.params.environment)
      
      echo "Updating yaml"
      sed -i "s#image: [a-zA-Z0-9|.\/|-]*:[a-zA-Z0-9|.]*#image: $(inputs.params.imageName)#" deployment.yaml

      cat deployment.yaml
      git add -u
      git commit -m "[tekton] updating deployment"
      git push

      
---
